# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.sde_get_nDims <- function(sdeptr) {
    .Call(`_msde_sde_get_nDims`, sdeptr)
}

.sde_get_nParams <- function(sdeptr) {
    .Call(`_msde_sde_get_nParams`, sdeptr)
}

