// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// sde_get_nDims
int sde_get_nDims(SEXP sdeptr);
RcppExport SEXP _msde_sde_get_nDims(SEXP sdeptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sdeptr(sdeptrSEXP);
    rcpp_result_gen = Rcpp::wrap(sde_get_nDims(sdeptr));
    return rcpp_result_gen;
END_RCPP
}
// sde_get_nParams
int sde_get_nParams(SEXP sdeptr);
RcppExport SEXP _msde_sde_get_nParams(SEXP sdeptrSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type sdeptr(sdeptrSEXP);
    rcpp_result_gen = Rcpp::wrap(sde_get_nParams(sdeptr));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_msde_sde_get_nDims", (DL_FUNC) &_msde_sde_get_nDims, 1},
    {"_msde_sde_get_nParams", (DL_FUNC) &_msde_sde_get_nParams, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_msde(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
