# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.Cobj_eval <- function(Cobj_ptr, y) {
    .Call(`_msde2_Cobj_eval`, Cobj_ptr, y)
}

.Cobj_setx <- function(Cobj_ptr, x) {
    invisible(.Call(`_msde2_Cobj_setx`, Cobj_ptr, x))
}

.Cobj_getx <- function(Cobj_ptr) {
    .Call(`_msde2_Cobj_getx`, Cobj_ptr)
}

.sde_nParams <- function(sdeptr) {
    .Call(`_msde2_sde_nParams`, sdeptr)
}

.sde_nDims <- function(sdeptr) {
    .Call(`_msde2_sde_nDims`, sdeptr)
}

.sde_isData <- function(sdeptr, xIn, thetaIn, singleX, singleTheta, nReps) {
    .Call(`_msde2_isData`, sdeptr, xIn, thetaIn, singleX, singleTheta, nReps)
}

.sde_isParams <- function(sdeptr, thetaIn, nReps) {
    .Call(`_msde2_isParams`, sdeptr, thetaIn, nReps)
}

.sde_Drift <- function(sdeptr, xIn, thetaIn, singleX, singleTheta, nReps) {
    .Call(`_msde2_Drift`, sdeptr, xIn, thetaIn, singleX, singleTheta, nReps)
}

.sde_Diff <- function(sdeptr, xIn, thetaIn, singleX, singleTheta, nReps) {
    .Call(`_msde2_Diff`, sdeptr, xIn, thetaIn, singleX, singleTheta, nReps)
}

.sde_Loglik <- function(sdeptr, xIn, dTIn, thetaIn, nComp, nReps, singleX, singleTheta, nCores) {
    .Call(`_msde2_LogLik`, sdeptr, xIn, dTIn, thetaIn, nComp, nReps, singleX, singleTheta, nCores)
}

.sde_Prior <- function(sdeptr, thetaIn, xIn, singleTheta, singleX, nReps, phiIn) {
    .Call(`_msde2_Prior`, sdeptr, thetaIn, xIn, singleTheta, singleX, nReps, phiIn)
}

.sde_Sim <- function(sdeptr, nDataOut, N, burn, reps, r, dT, MAXBAD, initData, params, singleX, singleTheta) {
    .Call(`_msde2_Sim`, sdeptr, nDataOut, N, burn, reps, r, dT, MAXBAD, initData, params, singleX, singleTheta)
}

.sde_Post <- function(sdeptr, initParams, initData, dT, nDimsPerObs, fixedParams, nSamples, burn, nParamsOut, nDataOut, dataOutSmp, dataOutComp, dataOutDims, updateParams, updateData, priorArgs, tunePar, updateLogLik, nLogLikOut, updateLastMiss, nLastMissOut, nCores) {
    .Call(`_msde2_Post`, sdeptr, initParams, initData, dT, nDimsPerObs, fixedParams, nSamples, burn, nParamsOut, nDataOut, dataOutSmp, dataOutComp, dataOutDims, updateParams, updateData, priorArgs, tunePar, updateLogLik, nLogLikOut, updateLastMiss, nLastMissOut, nCores)
}

